### ISSUE TITLE
Issue with Sigur Ros shows

### ISSUE THREAD

**Issue by greyhoundforty** [plamere/SetListener#7]
Whenever I use the site to try and save a Sigur Ros show it errors out. I have even provided the direct URL from Setlist.fm but it always returns:

```
Trouble!
Trouble saving that playlist.
```

An example setlist would be - http://www.setlist.fm/setlist/sigur-ros/2016/skeppsholmen-stockholm-sweden-53ff4fc1.html

**Comment by effex100** [comment]
I'm having the same problem with a set list for Touche Amore. My guess is both our issues are because the band names include accent characters.

Here is the set list that was erroring out for me: http://www.setlist.fm/setlist/touche-amore/2016/launchpad-albuquerque-nm-1bfc810c.html

**Comment by bszeti** [comment]
Anybody knows if SetListener is still alive?
It doesn't seem to work at the moment (no response from search api): 
http://static.echonest.com/SetListener/
